/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.screen;

import java.awt.Toolkit;

/**
 *
 * @author vivis
 */
public class AgendaVistoria extends javax.swing.JFrame {

    private String motivo = null;
    /**
     * Creates new form AgendaVistoria
     */
    public AgendaVistoria() {
        initComponents();
        setIcon();
        lblDetalheMotivo.setVisible(false);
        rdbtnDetalheMotivo1.setVisible(false);
        rdbtnDetalheMotivo2.setVisible(false);
        lblDadosMotivacao.setVisible(false);
        lblNomeMotivo.setVisible(false);
        txtNomeDenunciante.setVisible(false);
        lblTipoRetorno.setVisible(false);
        ckbEmail.setVisible(false);
        ckbCarta.setVisible(false);
        ckbLigacao.setVisible(false);
        lblDadoRetorno.setVisible(false);
        txtDadoRetorno.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gpbtnMotivo = new javax.swing.ButtonGroup();
        gpbtnDetalhe = new javax.swing.ButtonGroup();
        titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblData = new javax.swing.JLabel();
        lblDenuncia = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        rdbtnDetalheMotivo1 = new javax.swing.JRadioButton();
        lblLocal = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        lblLocal4 = new javax.swing.JLabel();
        lblLocal3 = new javax.swing.JLabel();
        lblLocal2 = new javax.swing.JLabel();
        lblLocal1 = new javax.swing.JLabel();
        lblLocal5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        lblLocal6 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        lblLocal7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        lblDadosMotivacao = new javax.swing.JLabel();
        lblNomeMotivo = new javax.swing.JLabel();
        lblTipoRetorno = new javax.swing.JLabel();
        lblDadoRetorno = new javax.swing.JLabel();
        txtNomeDenunciante = new javax.swing.JTextField();
        btnGravar = new javax.swing.JButton();
        lblData1 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDadoRetorno = new javax.swing.JTextArea();
        ckbEmail = new javax.swing.JCheckBox();
        ckbCarta = new javax.swing.JCheckBox();
        ckbLigacao = new javax.swing.JCheckBox();
        rdbtnOutro = new javax.swing.JRadioButton();
        rdbtnSolicitacao = new javax.swing.JRadioButton();
        rdbtnDenuncia = new javax.swing.JRadioButton();
        rdbtnDetalheMotivo2 = new javax.swing.JRadioButton();
        lblDetalheMotivo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);

        titulo.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Agendamento de Vistoria");

        lblData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblData.setText("Data Vistoria");

        lblDenuncia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDenuncia.setText("MOTIVAÇÃO");

        jTextField4.setToolTipText("Informe o bairro...");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        gpbtnDetalhe.add(rdbtnDetalheMotivo1);
        rdbtnDetalheMotivo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbtnDetalheMotivo1.setText("rdbtnDetalheMotivo1");
        rdbtnDetalheMotivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnDetalheMotivo1ActionPerformed(evt);
            }
        });

        lblLocal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLocal.setText("DADOS VISTORIA");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Avenida", "Alameda", "Praça", "Rua", "Travessia" }));

        jTextField1.setToolTipText("Informe o logradouro...");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setToolTipText("Informe o número...");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setToolTipText("Informe o complemento (se houver)...");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        lblLocal4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLocal4.setText("Complemento");

        lblLocal3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLocal3.setText("Número");

        lblLocal2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLocal2.setText("Logradouro");

        lblLocal1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLocal1.setText("Tipo Logradouro");

        lblLocal5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLocal5.setText("Bairro");

        jTextField5.setToolTipText("Informe o bairro...");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        lblLocal6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLocal6.setText("Município");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Belo Horizonte", "Corinto", "Itabirito", "João Monlevade", "Mariana", "Ouro Preto", " ", " ", " " }));

        lblLocal7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLocal7.setText("UF");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Minas Gerais" }));

        lblDadosMotivacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDadosMotivacao.setText("DADOS");

        lblNomeMotivo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeMotivo.setText("Nome");

        lblTipoRetorno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTipoRetorno.setText("Tipo Retorno");

        lblDadoRetorno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDadoRetorno.setText("Contato");
        lblDadoRetorno.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtNomeDenunciante.setToolTipText("Informe o logradouro...");
        txtNomeDenunciante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeDenuncianteActionPerformed(evt);
            }
        });

        btnGravar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        lblData1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblData1.setText("Responsável");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Jarbas Comemato", "Marcilene Sentanopudim", "Marlon Soares" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        txtDadoRetorno.setColumns(20);
        txtDadoRetorno.setRows(5);
        jScrollPane1.setViewportView(txtDadoRetorno);

        ckbEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ckbEmail.setText("E-mail");
        ckbEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbEmailActionPerformed(evt);
            }
        });

        ckbCarta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ckbCarta.setText("Carta");
        ckbCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbCartaActionPerformed(evt);
            }
        });

        ckbLigacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ckbLigacao.setText("Ligação");
        ckbLigacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbLigacaoActionPerformed(evt);
            }
        });

        gpbtnMotivo.add(rdbtnOutro);
        rdbtnOutro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbtnOutro.setText("Interna");
        rdbtnOutro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnOutroActionPerformed(evt);
            }
        });

        gpbtnMotivo.add(rdbtnSolicitacao);
        rdbtnSolicitacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbtnSolicitacao.setText("Solicitação");
        rdbtnSolicitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnSolicitacaoActionPerformed(evt);
            }
        });

        gpbtnMotivo.add(rdbtnDenuncia);
        rdbtnDenuncia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbtnDenuncia.setText("Denúncia");
        rdbtnDenuncia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnDenunciaActionPerformed(evt);
            }
        });

        gpbtnDetalhe.add(rdbtnDetalheMotivo2);
        rdbtnDetalheMotivo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbtnDetalheMotivo2.setText("rdbtnDetalheMotivo2");
        rdbtnDetalheMotivo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnDetalheMotivo2ActionPerformed(evt);
            }
        });

        lblDetalheMotivo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDetalheMotivo.setText("lblDetalheMotivo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblData)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblLocal1)
                                            .addComponent(lblLocal3)
                                            .addComponent(lblLocal5))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 149, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblLocal7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblData1)
                                            .addComponent(lblLocal2))
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBox4, 0, 378, Short.MAX_VALUE)
                                            .addComponent(jTextField1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblLocal4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(lblLocal6)
                                                .addGap(59, 59, 59)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField3)
                                            .addComponent(jComboBox3, 0, 375, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDenuncia)
                                .addGap(30, 30, 30)
                                .addComponent(rdbtnDenuncia)
                                .addGap(20, 20, 20)
                                .addComponent(rdbtnSolicitacao)
                                .addGap(20, 20, 20)
                                .addComponent(rdbtnOutro)
                                .addGap(100, 100, 100)
                                .addComponent(lblDetalheMotivo)
                                .addGap(30, 30, 30)
                                .addComponent(rdbtnDetalheMotivo1)
                                .addGap(18, 18, 18)
                                .addComponent(rdbtnDetalheMotivo2))
                            .addComponent(lblDadosMotivacao)
                            .addComponent(lblLocal)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDadoRetorno)
                                    .addComponent(lblNomeMotivo))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(txtNomeDenunciante, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(lblTipoRetorno)
                                        .addGap(20, 20, 20)
                                        .addComponent(ckbEmail)
                                        .addGap(20, 20, 20)
                                        .addComponent(ckbCarta)
                                        .addGap(20, 20, 20)
                                        .addComponent(ckbLigacao))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(283, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDenuncia)
                    .addComponent(rdbtnDenuncia)
                    .addComponent(rdbtnSolicitacao)
                    .addComponent(rdbtnOutro)
                    .addComponent(lblDetalheMotivo)
                    .addComponent(rdbtnDetalheMotivo1)
                    .addComponent(rdbtnDetalheMotivo2))
                .addGap(40, 40, 40)
                .addComponent(lblDadosMotivacao)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeMotivo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTipoRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ckbEmail)
                        .addComponent(ckbCarta)
                        .addComponent(ckbLigacao)
                        .addComponent(txtNomeDenunciante, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDadoRetorno)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblLocal)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(lblData1)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocal1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLocal2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocal3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLocal4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLocal5)
                    .addComponent(lblLocal6)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocal7)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(156, 156, 156))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void txtNomeDenuncianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeDenuncianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeDenuncianteActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        
    }//GEN-LAST:event_btnGravarActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void ckbEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbEmailActionPerformed
        txtDadoRetorno.setText("\nE-mail: ");
    }//GEN-LAST:event_ckbEmailActionPerformed

    private void ckbCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbCartaActionPerformed
        txtDadoRetorno.setText("\nEndereço: ");
    }//GEN-LAST:event_ckbCartaActionPerformed

    private void ckbLigacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbLigacaoActionPerformed
        txtDadoRetorno.setText("\nTelefone: ");
    }//GEN-LAST:event_ckbLigacaoActionPerformed

    private void rdbtnDetalheMotivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnDetalheMotivo1ActionPerformed
        if("Denúncia".equals(this.motivo)){
        
        rdbtnDetalheMotivo1.setSelected(false);
        lblDadosMotivacao.setVisible(false);
        lblNomeMotivo.setVisible(false);
        txtNomeDenunciante.setVisible(false);
        lblTipoRetorno.setVisible(false);
        ckbEmail.setVisible(false);
        ckbCarta.setVisible(false);
        ckbLigacao.setVisible(false);
        lblDadoRetorno.setVisible(false);
        txtDadoRetorno.setVisible(false);
        }else if("Solicitação".equals(this.motivo)){
        
            lblDadosMotivacao.setVisible(true);
            lblNomeMotivo.setVisible(true);
            txtNomeDenunciante.setVisible(true);
            lblTipoRetorno.setVisible(true);
            ckbEmail.setVisible(true);
            ckbCarta.setVisible(true);
            ckbLigacao.setVisible(true);
            lblDadoRetorno.setVisible(true);
            txtDadoRetorno.setVisible(true);
    }
    }//GEN-LAST:event_rdbtnDetalheMotivo1ActionPerformed

    private void rdbtnOutroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnOutroActionPerformed
        rdbtnDetalheMotivo1.setSelected(false);
        lblDadosMotivacao.setVisible(false);
        lblNomeMotivo.setVisible(false);
        txtNomeDenunciante.setVisible(false);
        lblTipoRetorno.setVisible(false);
        ckbEmail.setVisible(false);
        ckbCarta.setVisible(false);
        ckbLigacao.setVisible(false);
        lblDadoRetorno.setVisible(false);
        txtDadoRetorno.setVisible(false);
        
        lblDetalheMotivo.setVisible(false);
        rdbtnDetalheMotivo1.setVisible(false);
        rdbtnDetalheMotivo2.setVisible(false);
    }//GEN-LAST:event_rdbtnOutroActionPerformed

    private void rdbtnSolicitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnSolicitacaoActionPerformed
        
        lblDetalheMotivo.setText("Tipo");
        lblDetalheMotivo.setVisible(true);
        rdbtnDetalheMotivo1.setText("Particular");
        rdbtnDetalheMotivo1.setSelected(true);
        rdbtnDetalheMotivo1.setVisible(true);
        rdbtnDetalheMotivo2.setText("Órgãos Públicos");
        rdbtnDetalheMotivo2.setSelected(false);
        rdbtnDetalheMotivo2.setVisible(true);
        lblDadosMotivacao.setText("DADOS SOLICITANTE");
        rdbtnDetalheMotivo1.setSelected(true);
        rdbtnDetalheMotivo1.setSelected(false);
        lblDadosMotivacao.setVisible(true);
        lblNomeMotivo.setVisible(true);
        txtNomeDenunciante.setVisible(true);
        lblTipoRetorno.setVisible(true);
        ckbEmail.setVisible(true);
        ckbCarta.setVisible(true);
        ckbLigacao.setVisible(true);
        lblDadoRetorno.setVisible(true);
        txtDadoRetorno.setVisible(true);
        this.motivo = "Solicitação";
    }//GEN-LAST:event_rdbtnSolicitacaoActionPerformed

    private void rdbtnDenunciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnDenunciaActionPerformed

        lblDetalheMotivo.setText("Tipo");
        lblDetalheMotivo.setVisible(true);
        rdbtnDetalheMotivo1.setText("Anônima");
        rdbtnDetalheMotivo1.setSelected(true);
        rdbtnDetalheMotivo1.setVisible(true);
        rdbtnDetalheMotivo2.setText("Identificada");
        rdbtnDetalheMotivo2.setSelected(false);
        rdbtnDetalheMotivo2.setVisible(true);
        lblDadosMotivacao.setText("DADOS DENUNCIANTE");
        lblNomeMotivo.setText("Denunciante");
        this.motivo = "Denúncia";


    }//GEN-LAST:event_rdbtnDenunciaActionPerformed

    private void rdbtnDetalheMotivo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnDetalheMotivo2ActionPerformed
//        rdbtnDetalheMotivo1.setSelected(false);
//        lblDadosMotivacao.setEnabled(true);
//        lblNomeMotivo.setEnabled(true);
//        txtNomeDenunciante.setEnabled(true);
//        lblTipoRetorno.setEnabled(true);
//        ckbEmail.setEnabled(true);
//        ckbCarta.setEnabled(true);
//        ckbLigacao.setEnabled(true);
//        lblDadoRetorno.setEnabled(true);
//        txtDadoRetorno.setEnabled(true);
       
        rdbtnDetalheMotivo1.setSelected(false);
        lblDadosMotivacao.setVisible(true);
        lblNomeMotivo.setVisible(true);
        txtNomeDenunciante.setVisible(true);
        lblTipoRetorno.setVisible(true);
        ckbEmail.setVisible(true);
        ckbCarta.setVisible(true);
        ckbLigacao.setVisible(true);
        lblDadoRetorno.setVisible(true);
        txtDadoRetorno.setVisible(true);
        
    }//GEN-LAST:event_rdbtnDetalheMotivo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaVistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaVistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaVistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaVistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaVistoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGravar;
    private javax.swing.JCheckBox ckbCarta;
    private javax.swing.JCheckBox ckbEmail;
    private javax.swing.JCheckBox ckbLigacao;
    private javax.swing.ButtonGroup gpbtnDetalhe;
    private javax.swing.ButtonGroup gpbtnMotivo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lblDadoRetorno;
    private javax.swing.JLabel lblDadosMotivacao;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblData1;
    private javax.swing.JLabel lblDenuncia;
    private javax.swing.JLabel lblDetalheMotivo;
    private javax.swing.JLabel lblLocal;
    private javax.swing.JLabel lblLocal1;
    private javax.swing.JLabel lblLocal2;
    private javax.swing.JLabel lblLocal3;
    private javax.swing.JLabel lblLocal4;
    private javax.swing.JLabel lblLocal5;
    private javax.swing.JLabel lblLocal6;
    private javax.swing.JLabel lblLocal7;
    private javax.swing.JLabel lblNomeMotivo;
    private javax.swing.JLabel lblTipoRetorno;
    private javax.swing.JRadioButton rdbtnDenuncia;
    private javax.swing.JRadioButton rdbtnDetalheMotivo1;
    private javax.swing.JRadioButton rdbtnDetalheMotivo2;
    private javax.swing.JRadioButton rdbtnOutro;
    private javax.swing.JRadioButton rdbtnSolicitacao;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextArea txtDadoRetorno;
    private javax.swing.JTextField txtNomeDenunciante;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the motivo
     */
    public String getMotivo() {
        return motivo;
    }

    /**
     * @param motivo the motivo to set
     */
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
