-- MySQL Script generated by MySQL Workbench
-- Sun Nov  3 12:48:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sisgefa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sisgefa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sisgefa` DEFAULT CHARACTER SET utf8 ;
USE `sisgefa` ;


-----------------------------------------------------
-- Table `sisgefa`.`funcionario`
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgefa`.`funcionario` (
  `cpf` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `funcao` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(15) NOT NULL,
  `setor`VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-----------------------------------------------------
-- Popula `sisgefa`.`funcionario`
-- --------------------------------------------------

INSERT INTO `sisgefa`.`funcionario`(`cpf`,`nome`,`funcao`,`senha`,`setor`)VALUES('12345678910', 'Marlon Grisalho', 'Fiscal', 'senha123', 'Fiscalização');
INSERT INTO `sisgefa`.`funcionario`(`cpf`,`nome`,`funcao`,`senha`,`setor`)VALUES('12345678911', 'Jarbas Comemato', 'Fiscal', 'senha123', 'Licenciamento');
INSERT INTO `sisgefa`.`funcionario`(`cpf`,`nome`,`funcao`,`senha`,`setor`)VALUES('12345678912', 'Marcilene Deitanopudim', 'Fiscal', 'senha123', 'Fiscalização');

-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `sisgefa`.`VISTORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgefa`.`vistoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(20) NOT NULL,
  `local` VARCHAR(100) NOT NULL,
  `denuncia` CHAR(1) NOT NULL,
  `relatorio` VARCHAR(100) NULL,
  `funcionario_cpf` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id`, `funcionario_CPF`),
  INDEX `fk_vistoria_funcionario_idx` (`funcionario_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_vistoria_funcionario`
    FOREIGN KEY (`funcionario_cpf`)
    REFERENCES `sisgefa`.`funcionario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgefa`.`uf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgefa`.`uf` (
  `codigo` VARCHAR(2) NOT NULL,
  `nome` VARCHAR(20) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Popula `sisgefa`.`uf`
-- -----------------------------------------------------
INSERT INTO `sisgefa`.`uf` (`codigo`, `nome`) VALUES ("MG", "Minas Gerais");
-- --  ----------------------------------------

-- -----------------------------------------------------
-- Table `sisgefa`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgefa`.`municipio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `uf_codigo` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`, `uf_codigo`),
  INDEX `fk_municipio_uf_idx` (`uf_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_municipio_uf`
    FOREIGN KEY (`uf_codigo`)
    REFERENCES `sisgefa`.`uf` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';

-- -----------------------------------------------------
-- Popula `sisgefa`.`municipio`
-- -----------------------------------------------------
INSERT INTO `sisgefa`.`municipio` (`nome`,`uf_codigo`) VALUES ("Belo Horizonte", "MG");
INSERT INTO `sisgefa`.`municipio` (`nome`,`uf_codigo`) VALUES ("Nova Lima", "MG");
INSERT INTO `sisgefa`.`municipio` (`nome`,`uf_codigo`) VALUES ("Itabirito", "MG");
INSERT INTO `sisgefa`.`municipio` (`nome`,`uf_codigo`) VALUES ("Ouro Preto", "MG");
INSERT INTO `sisgefa`.`municipio` (`nome`,`uf_codigo`) VALUES ("Mariana", "MG");
INSERT INTO `sisgefa`.`municipio` (`nome`,`uf_codigo`) VALUES ("João Monlevade", "MG");
INSERT INTO `sisgefa`.`municipio` (`nome`,`uf_codigo`) VALUES ("Corinto", "MG");

-- --  ----------------------------------------

-- -----------------------------------------------------
-- Table `sisgefa`.`tipo_logradouro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgefa`.`tipo_logradouro` (
  `codigo` VARCHAR(10) NOT NULL,
  `descricao` VARCHAR(20) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Popula `sisgefa`.`tipo_logradouro`
-- -----------------------------------------------------
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("AC", "Acesso");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("AD", "Adro");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("AL", "Alameda");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("AT", "Alto");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("ATL", "Atalho");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("AV", "Avenida");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("BAL", "Balneário");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("BELV", "Belvedere");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("BC", "Beco");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("BL", "Bloco");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("BSQ", "Bosque");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("BVD", "Boulevard");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("BX", "Baixa");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("C", "Cais");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("CAM", "Caminho");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("CHAP", "Chapadão");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("CJ", "Conjunto");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("COL", "Colônia");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("COR", "Corredor");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("CPO", "Campo");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("CRG", "Córrego");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("DSV", "Desvio");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("DT", "Distrito");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("ESC", "Escada");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("EST", "Estrada");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("ETC", "Estação");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("ETD", "Estádio");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("FAV", "Favela");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("FAZ", "Fazenda");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("FER", "Ferrovia");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("FNT", "Fonte");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("FRA", "Feira");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("FTE", "Forte");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("GAL", "Galeria");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("GJA", "Granja");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("IA", "Ilha");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("JD", "Jardim");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("LD", "Ladeira");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("LRG", "Largo");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("LGA", "Lagoa");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("LOT", "Loteamento");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("MRO", "Morro");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("TEM", "Monte");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("PAR", "Paralela");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("PAS", "Passeio");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("PAT", "Pátio");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("PC", "Praça");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("PDA", "Parada");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("PR", "Praia");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("PRL", "Prolongamento");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("PRQ", "Parque");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("PSA", "Passarela");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("PSG", "Passagem");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("PTE", "Ponte");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("Q", "Quadra");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("QTA", "Quinta");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("R", "Rua");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("RAM", "Ramal");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("REC", "Recanto");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("RER", "Retiro");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("RET", "Reta");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("ROD", "Rodovia");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("RTN", "Retorno");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("SIT", "Sítio");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("SRV", "Servidão");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("ST", "Setor");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("SUB", "Subida");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("TCH", "Trincheira");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("TER", "Terminal");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("TRV", "Trevo");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("TV", "Travessa");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("V", "Via");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("VD", "Viaduto");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("VL", "Vila");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("VLA", "Viela");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("VLE", "Vale");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("ZIG-ZAG", "Zigue-Zague");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("TRC", "Trecho");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("VER", "Vereda");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("ART", "Artéria");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("EVD", "Elevada");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("PTO", "Porto");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("BLO", "Balão");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("PDO", "Paradouro");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("A", "Área");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("JDE", "Jardinete");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("ESP", "Esplanada");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("QTAS", "Quintas");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("ROT", "Rótula");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("MNA", "Marina");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("DSC", "Descida");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("CIRC", "Circular");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("UNID", "Unidade");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("CH", "Chácara");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("RMP", "Rampa");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("PNT", "Ponta");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("V-PED", "Via de Pedestre");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("COND", "Condomínio");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("HAB", "Habitacional");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("RES", "Residencial");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("CAN", "Canal");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("BCO", "Buraco");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("MOD", "Módulo");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("ETN", "Estância");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("LG", "Lago");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("NUC", "Núcleo");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("ERA", "Aeroporto");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("PSC-SUB", "Passagem Subterrânea");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("CMP-VR", "Complexo Viário");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("PC-ESP", "Praça de Esportes");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("V-EVD", "Via Elevado");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("RTT", "Rotatória");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("ESTC", "Estacionamento");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("VAL", "Vala");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("R-PED", "Rua de Pedestre");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("TUN", "Túnel");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("VRTE", "Variante");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("ROD-AN", "Rodo Anel");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("TV-PART", "Travessa Particular");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("CALC", "Calçada");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("V-AC", "AVia de Acesso");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("ENT-PART", "Entrada Particular");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("V-EXP", "Via Expressa");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("EST-MUN", "Estrada Municipal");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("AV-CONT", "Avenida Contorno");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("EQ", "Entre Quadra");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("R-LIG", "Rua de Ligação");
INSERT INTO sisgefa.tipo_logradouro (codigo, descricao) values ("AE", "Área Especial");

-- --  ----------------------------------------

-- -----------------------------------------------------
-- Table `sisgefa`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgefa`.`pessoa` (
  `cpf_cnpj` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(100) NULL,
  `rg` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  `telefone` VARCHAR(20) NULL,
  `logradouro` VARCHAR(100) NULL,
  `num_logradouro` INT NULL,
  `comp_logradouro` VARCHAR(45) NULL,
  `bairro_logradouro` VARCHAR(45) NULL,
  `pref_contato` VARCHAR(20) NULL,
  `municipio_id` INT NOT NULL,
  `municipio_uf_codigo` VARCHAR(2) NOT NULL,
  `tipo_logradouro_codigo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`cpf_cnpj`),
  INDEX `fk_pessoa_municipio_idx` (`municipio_id` ASC, `municipio_uf_codigo` ASC) VISIBLE,
  INDEX `fk_pessoa_tipo_logradouro_idx` (`tipo_logradouro_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_municipio`
    FOREIGN KEY (`municipio_id` , `municipio_uf_codigo`)
    REFERENCES `sisgefa`.`municipio` (`id` , `uf_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_tipo_logradouro`
    FOREIGN KEY (`tipo_logradouro_codigo`)
    REFERENCES `sisgefa`.`tipo_logradouro` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -- -----------------------------------------------------
-- -- Table `sisgefa`.`tipo_denuncia`
-- -- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgefa`.`tipo_denuncia` (
  `codigo` CHAR NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Popula `sisgefa`.`tipo_denuncia`
-- ---------------------------------------------------
INSERT INTO `sisgefa`.`tipo_denuncia` (`codigo`,`descricao`) VALUES ("A", "Anônima");
INSERT INTO `sisgefa`.`tipo_denuncia` (`codigo`,`descricao`) VALUES ("I", "Identificada");
--  ----------------------------------------

-- -- -----------------------------------------------------
-- -- Table `sisgefa`.`status`
-- -- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgefa`.`status` (
  `codigo` CHAR(2) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Popula `sisgefa`.`status`
-- ---------------------------------------------------
INSERT INTO `sisgefa`.`status` (`codigo`,`descricao`) VALUES ("N", "Nova");
INSERT INTO `sisgefa`.`status` (`codigo`,`descricao`) VALUES ("E", "Encaminhada");
INSERT INTO `sisgefa`.`status` (`codigo`,`descricao`) VALUES ("AV", "Aguardando Vistoria");
INSERT INTO `sisgefa`.`status` (`codigo`,`descricao`) VALUES ("AT", "Atendida");
--  ----------------------------------------


-- -----------------------------------------------------
-- Table `sisgefa`.`denuncia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgefa`.`denuncia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_denuncia_codigo` CHAR NOT NULL,
  `data` VARCHAR(20) NOT NULL,
  `denunciado` VARCHAR(100) NOT NULL,
  `tipo_logradouro_codigo` VARCHAR(10) NULL ,
  `logradouro` VARCHAR(100) NULL,
  `num_logradouro` INT NULL,
  `compl_logradouro` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `municipio_id` INT NOT NULL,
  `municipio_uf_codigo` VARCHAR(2) NOT NULL,
  `pto_referencia` VARCHAR(100) NULL,
  `descricao` VARCHAR(2000) NOT NULL,
  `pessoa_id` VARCHAR(20) NULL ,
  `status` CHAR(2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_denuncia_municipio_idx` (`municipio_id` ASC, `municipio_uf_codigo` ASC) VISIBLE,
  INDEX `fk_denuncia_tipo_logradouro_idx` (`tipo_logradouro_codigo` ASC) VISIBLE,
  INDEX `fk_denuncia_tipo_denuncia_idx` (`tipo_denuncia_codigo` ASC) VISIBLE,
  INDEX `fk_denuncia_pessoa_idx` (`pessoa_id` ASC) VISIBLE,
  CONSTRAINT `fk_denuncia_municipio`
    FOREIGN KEY (`municipio_id` , `municipio_uf_codigo`)
    REFERENCES `sisgefa`.`municipio` (`id` , `uf_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_denuncia_tipo_logradouro`
  FOREIGN KEY (`tipo_logradouro_codigo`)
  REFERENCES `sisgefa`.`tipo_logradouro` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_denuncia_tipo_denuncia`
    FOREIGN KEY (`tipo_denuncia_codigo`)
    REFERENCES `sisgefa`.`tipo_denuncia` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_denuncia_pessoa`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `sisgefa`.`pessoa` (`cpf_cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgefa`.`arquivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgefa`.`arquivos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `denuncia_id` INT NOT NULL,
  `caminho` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`, `denuncia_id`),
  INDEX `fk_arquivos_denuncia_idx` (`denuncia_id` ASC) VISIBLE,
  CONSTRAINT `fk_arquivos_denuncia`
    FOREIGN KEY (`denuncia_id`)
    REFERENCES `sisgefa`.`denuncia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- ------------------------------------------------
-- INCLUIR CONFIGURAÇÕES NA CRIAÇÃO DO BANCO
-- ------------------------------------------------

-- ------------------------------------------------

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
