-- MySQL Script generated by MySQL Workbench
-- Sat Nov  2 21:33:40 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sisgefa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sisgefa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sisgefa` DEFAULT CHARACTER SET utf8 ;
USE `sisgefa` ;

-- -----------------------------------------------------
-- Table `sisgefa`.`uf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgefa`.`uf` (
  `id` INT NOT NULL,
  `nome` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgefa`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgefa`.`municipio` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `uf_id` INT NOT NULL,
  PRIMARY KEY (`id`, `uf_id`),
  INDEX `fk_municipio_uf1_idx` (`uf_id` ASC) VISIBLE,
  CONSTRAINT `fk_municipio_uf1`
    FOREIGN KEY (`uf_id`)
    REFERENCES `sisgefa`.`uf` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `sisgefa`.`tipo_logradouro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgefa`.`tipo_logradouro` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgefa`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgefa`.`pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `rg` VARCHAR(20) NULL,
  `cpf_cnpj` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  `telefone` VARCHAR(20) NULL,
  `logradouro` VARCHAR(100) NULL,
  `num_logradouro` INT NULL,
  `comp_logradouro` VARCHAR(45) NULL,
  `bairro_logradouro` VARCHAR(45) NULL,
  `pref_contato` VARCHAR(20) NULL,
  `municipio_id` INT NOT NULL,
  `municipio_uf_id` INT NOT NULL,
  `tipo_logradouro_id` INT NOT NULL,
  PRIMARY KEY (`id`, `municipio_id`, `municipio_uf_id`, `tipo_logradouro_id`),
  UNIQUE INDEX `cpf_cnpj_UNIQUE` (`cpf_cnpj` ASC) VISIBLE,
  INDEX `fk_pessoa_municipio1_idx` (`municipio_id` ASC, `municipio_uf_id` ASC) VISIBLE,
  INDEX `fk_pessoa_tipo_logradouro1_idx` (`tipo_logradouro_id` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_municipio1`
    FOREIGN KEY (`municipio_id` , `municipio_uf_id`)
    REFERENCES `sisgefa`.`municipio` (`id` , `uf_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_tipo_logradouro1`
    FOREIGN KEY (`tipo_logradouro_id`)
    REFERENCES `sisgefa`.`tipo_logradouro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgefa`.`tipo_denuncia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgefa`.`tipo_denuncia` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgefa`.`denuncia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgefa`.`denuncia` (
  `id` INT NOT NULL,
  `denunciado` VARCHAR(100) NOT NULL,
  `logradouro` VARCHAR(100) NULL,
  `num_logradouro` INT NULL,
  `compl_logradouro` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `pto_referencia` VARCHAR(100) NULL,
  `descricao` VARCHAR(2000) NOT NULL,
  `pessoa_id` INT NOT NULL,
  `tipo_denuncia_id` INT NOT NULL,
  `municipio_id` INT NOT NULL,
  `municipio_uf_id` INT NOT NULL,
  PRIMARY KEY (`id`, `pessoa_id`, `tipo_denuncia_id`, `municipio_id`, `municipio_uf_id`),
  INDEX `fk_denuncia_pessoa1_idx` (`pessoa_id` ASC) VISIBLE,
  INDEX `fk_denuncia_tipo_denuncia1_idx` (`tipo_denuncia_id` ASC) VISIBLE,
  INDEX `fk_denuncia_municipio1_idx` (`municipio_id` ASC, `municipio_uf_id` ASC) VISIBLE,
  CONSTRAINT `fk_denuncia_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `sisgefa`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_denuncia_tipo_denuncia1`
    FOREIGN KEY (`tipo_denuncia_id`)
    REFERENCES `sisgefa`.`tipo_denuncia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_denuncia_municipio1`
    FOREIGN KEY (`municipio_id` , `municipio_uf_id`)
    REFERENCES `sisgefa`.`municipio` (`id` , `uf_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgefa`.`arquivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgefa`.`arquivos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `caminho` VARCHAR(150) NOT NULL,
  `denuncia_id` INT NOT NULL,
  PRIMARY KEY (`id`, `denuncia_id`),
  INDEX `fk_arquivos_denuncia1_idx` (`denuncia_id` ASC) VISIBLE,
  CONSTRAINT `fk_arquivos_denuncia1`
    FOREIGN KEY (`denuncia_id`)
    REFERENCES `sisgefa`.`denuncia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
