INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (1,"AC","Acesso");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (2,"AD","Adro");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (4,"AL","Alameda");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (5,"AT","Alto");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (7,"ATL","Atalho");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (8,"AV","Avenida");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (9,"BAL","Balneário");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (10,"BELV","Belvedere");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (11,"BC","Beco");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (12,"BL","Bloco");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (13,"BSQ","Bosque");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (14,"BVD","Boulevard");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (15,"BX","Baixa");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (16,"C","Cais");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (17,"CAM","Caminho");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (19,"CHAP","Chapadão");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (20,"CJ","Conjunto");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (21,"COL","Colônia");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (22,"COR","Corredor");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (23,"CPO","Campo");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (24,"CRG","Córrego");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (27,"DSV","Desvio");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (28,"DT","Distrito");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (30,"ESC","Escada");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (31,"EST","Estrada");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (32,"ETC","Estação");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (33,"ETD","Estádio");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (36,"FAV","Favela");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (37,"FAZ","Fazenda");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (38,"FER","Ferrovia");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (39,"FNT","Fonte");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (40,"FRA","Feira");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (43,"FTE","Forte");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (45,"GAL","Galeria");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (46,"GJA","Granja");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (50,"IA","Ilha");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (52,"JD","Jardim");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (53,"LD","Ladeira");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (54,"LRG","Largo");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (55,"LGA","Lagoa");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (56,"LOT","Loteamento");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (59,"MRO","Morro");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (60,"TEM","Monte");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (62,"PAR","Paralela");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (63,"PAS","Passeio");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (64,"PAT","Pátio");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (65,"PC","Praça");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (67,"PDA","Parada");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (70,"PR","Praia");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (71,"PRL","Prolongamento");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (72,"PRQ","Parque");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (73,"PSA","Passarela");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (74,"PSG","Passagem");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (76,"PTE","Ponte");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (77,"Q","Quadra");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (79,"QTA","Quinta");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (81,"R","Rua");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (82,"RAM","Ramal");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (87,"REC","Recanto");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (88,"RER","Retiro");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (89,"RET","Reta");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (90,"ROD","Rodovia");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (91,"RTN","Retorno");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (92,"SIT","Sítio");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (94,"SRV","Servidão");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (95,"ST","Setor");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (96,"SUB","Subida");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (97,"TCH","Trincheira");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (98,"TER","Terminal");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (99,"TRV","Trevo");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (100,"TV","Travessa");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (101,"V","Via");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (103,"VD","Viaduto");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (104,"VL","Vila");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (105,"VLA","Viela");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (106,"VLE","Vale");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (108,"ZIG-ZAG","Zigue-Zague");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (452,"TRC","Trecho");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (453,"VER","Vereda");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (465,"ART","Artéria");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (468,"EVD","Elevada");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (469,"PTO","Porto");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (470,"BLO","Balão");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (471,"PDO","Paradouro");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (472,"A","Área");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (473,"JDE","Jardinete");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (474,"ESP","Esplanada");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (475,"QTAS","Quintas");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (476,"ROT","Rótula");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (477,"MNA","Marina");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (478,"DSC","Descida");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (479,"CIRC","Circular");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (480,"UNID","Unidade");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (481,"CH","Chácara");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (482,"RMP","Rampa");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (483,"PNT","Ponta");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (484,"V-PED","Via de Pedestre");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (485,"COND","Condomínio");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (486,"HAB","Habitacional");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (487,"RES","Residencial");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (495,"CAN","Canal");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (496,"BCO","Buraco");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (497,"MOD","Módulo");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (498,"ETN","Estância");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (499,"LG","Lago");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (500,"NUC","Núcleo");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (501,"ERA","Aeroporto");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (502,"PSC-SUB","Passagem Subterrânea");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (503,"CMP-VR","Complexo Viário");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (504,"PC-ESP","Praça de Esportes");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (505,"V-EVD","Via Elevado");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (506,"RTT","Rotatória");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (564,"ESTC","Estacionamento");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (565,"VAL","Vala");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (566,"R-PED","Rua de Pedestre");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (567,"TUN","Túnel");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (568,"VRTE","Variante");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (569,"ROD-AN","Rodo Anel");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (570,"TV-PART","Travessa Particular");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (571,"CALC","Calçada");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (572,"V-AC","AVia de Acesso");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (573,"ENT-PART","Entrada Particular");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (645,"AL","Alameda");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (646,"V-EXP","Via Expressa");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (650,"EST-MUN","Estrada Municipal");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (651,"AV-CONT","Avenida Contorno");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (652,"EQ","Entre Quadra");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (653,"R-LIG","Rua de Ligação");
INSERT INTO sisgefa.tipo_logradouro (id, codigo, descricao) values (654,"AE","Área Especial");